export const studios = [
  'Tama Production',
  'Viewworks',
  'Seoul Movie',
  'Myung Films',
  'Studio Meditation With a Pencil',
  'Charaction',
  'Animation Studio Wagumi',
  'Stereotype',
  'Hoods Entertainment',
  'DC Impression Vision',
  'Dyna Method',
  'Studio 3Hz',
  'Executive Decision',
  'Studio Unicorn',
  'Twenty First',
  'TriF Studio',
  'VCRWORKS',
  '2:10 Animation',
  'P.I.C.S.',
  'Studio Bind',
  'Revoroot',
  'PHANTOM',
  'Studio Sign',
  'Elias',
  'Chaos Project',
  'Lingsanwu Animation',
  'OTOIRO',
  'Watanabe Promotion',
  'HORNETS',
  'Egg',
  'Zyc',
  'Studio March',
  'studio MOTHER',
  'HM Heros',
  'Xiaoming Taiji',
  "Children's Playground Entertainment",
  'Okumaza',
  'Tokyo Kids',
  "Rock'n Roll Mountain",
  'Studio CANDY BOX',
  'Shadow Steps',
  'Ripple Film',
  'Griot Groove',
  'Studio Egg',
  'Toho Interactive Animation',
  'Alice Production',
  'Hand to Mouse.',
  'Project Studio Q',
  'Liber',
  'Medo',
  'Chiptune',
  'Studio VOLN',
  'Passion Paint Animation',
  'Larx Entertainment',
  'PPM',
  'OLM Digital',
  '33 Collective',
  'Sasayuri',
  'NHK Art',
  'Minami Machi Bugyousho',
  'EKACHI EPILKA',
  'Higashinaka Studio',
  'Kino Production',
  'Pierrot Films',
  'Shirogumi',
  'Lide',
  '8bit',
  'Studio Hokiboshi',
  'Miyu Productions',
  'INTERFACEDOGS',
  'THREE IS A MAGIC NUMBER',
  'Amarcord',
  'Will Palette',
  'Story Effect',
  'GUMBLAB',
  'Mokai Technology',
  'P.A. Works',
  'Pancake',
  'Deck',
  'Namu Animation',
  'Yostar Pictures',
  'Schoolzone',
  'Meruhensha',
  'GIFTanimation',
  'ILCA',
  'Painting Dream',
  'ASK Animation Studio',
  'Studio Core',
  'Ordet',
  'Public & Basic',
  'Yamamura Animation, Inc.',
  'Making Animation',
  'Project Team Muu',
  'Studio Zero',
  'Studio Gazelle',
  'BeSTACK',
  'PONOS Corporation',
  'asread.',
  'Infinity Animations',
  'T-Rex',
  'SIDO LIMITED',
  'Studio Eromatick',
  'Sonsan Kikaku',
  'Red Dog Culture House',
  'Studio Izena',
  'Studio Vandal',
  'Joicy Studio',
  'Y.O.U.C',
  'OZ',
  'Graphinica',
  'Shochiku Animation Institute',
  'Thundray',
  'Delight Animation',
  'G-angle',
  'Super Normal Studio',
  'E&G Films',
  'Studio Nuck',
  'Imagica Digitalscape',
  'Angle',
  'Studio Kajino',
  'D.A.S.T Corporation',
  'Studio Khronos',
  'General Entertainment',
  'AIC Spirits',
  'Yi Chen Animation',
  'Marvy Jack',
  'Marui Group',
  'Space-X',
  'M.S.C',
  'Seven',
  'HOTZIPANG',
  'SAMG Entertainment',
  'Studio Flad',
  'Ishikawa Pro',
  'Yumeta Company',
  'Mikimoto Production',
  'Dawn Animation',
  'Kusama Art',
  'AIC Build',
  'Shinkuukan',
  'T.P.O',
  'Anima',
  'Lay-duce',
  'Live2D Creative Studio',
  'Studio Flag',
  'drop',
  'YHKT Entertainment',
  'Studio A. Craft',
  'Studio Jam',
  'Kazuki Production',
  'Felix Film',
  'Studio Binzo',
  'C-Station',
  'Nice Boat Animation',
  'trenova',
  'Urban Product',
  'Pastel',
  'The Monk Studios',
  'Qianqi Animation',
  'TOCSIS',
  'Durandal',
  'pH Studio',
  'Gambit',
  'Success Corp.',
  'Maboroshi Koubou',
  'Tsukimidou',
  'Studio Nanahoshi',
  'AIC Classic',
  'OB Planning',
  'Picograph',
  'Ga-Crew',
  'Rockwell Eyes',
  'I was a Ballerina',
  'Yamato Works',
  'Echo',
  'Hanho Heung-Up',
  'Shimogumi',
  'Digital Dream Studios',
  'Saber Works',
  'Sunrise',
  'AYCO',
  'WHOPPERS',
  'Encourage Films',
  'Qzil.la',
  'Milky Cartoon',
  'Studio Shelter',
  'Yaoyorozu',
  'Reirs',
  'teamKG',
  'Xanthus Media',
  'LX Animation Studio',
  'Pony Canyon',
  'Wolf Smoke Studio',
  'foodunited.',
  'CloverWorks',
  'Kigumi',
  'Aurora Animation',
  'Samsara Animation Studio',
  'Hai An Xian Donghua Gongzuo Shi',
  'LinQ',
  'SPEED',
  'Studio Crocodile',
  'SAFEHOUSE',
  'Village Studio',
  'Lead',
  'Marvelous Entertainment',
  'Lapin Track',
  'StudioRF Inc.',
  'Idol',
  'Rising Force',
  'Front Line',
  'Three-d',
  'Cocktail Media',
  'Studio Signal',
  'Project No.9',
  'PRA',
  'PINE JAM',
  'Misogo Animation Studio',
  'Fanworks',
  'Sparkly Key Animation Studio',
  'qmotri',
  'Shykeumo Animation Studio',
  'Takahashi Studio',
  'Jichitai Anime',
  'CompTown',
  'Space Neko Company',
  'Flat Studio',
  'Fifth Avenue',
  'Original Dream',
  'Xing Yi Kai Chen',
  'Djinn Power',
  'A.C.G.T.',
  'NAZ',
  'Studio Massket',
  'Twin Engine',
  'Synergy Japan',
  'Taikong Works',
  'Zuiyo',
  'LandQ studios',
  'Olive Studio',
  'B&T',
  'Mirai Film',
  'Studio Yona',
  'Studio Placebo',
  'The Answer Studio',
  'Haoliners Animation League',
  'Arvo Animation',
  'Tokyo Movie Shinsha',
  'Production IMS',
  'Wulifang',
  'Koinrush Studio',
  "Monster's Egg",
  'Iconix Entertainment',
  'Fantawild Animation',
  'Tong Ming Xuan',
  'GEMBA',
  'LAN Studio',
  'l-a-unch・BOX',
  'Studio CA',
  'REALTHING',
  'maroyaka',
  'MORIE Inc.',
  'Shogakukan-Shueisha Productions',
  'Studio PuYUKAI',
  'KAGAYA Studio',
  'ARECT',
  'Mousou Senka',
  'Kyoto Animation',
  'Remic',
  'Square Pictures',
  'Millepensee',
  'TOHO animation',
  'production doA',
  'Studio Daisy',
  'Group TAC',
  'BlueArc Animation Studios',
  'Palm Studio',
  'Shanghai Animation Film Studio',
  'Animation 501',
  'Bebow',
  'Konami animation',
  'Iyasakadou Film',
  'Taiko Studios',
  'CUKA',
  'Marine Entertainment',
  'Media Factory',
  'THINKR',
  'Maro Studio',
  'White Fox',
  'TUBA',
  'Genco',
  'Joker Films',
  'October Media',
  'Wako Productions',
  'Collaboration Works',
  'Fortes',
  'Eshoya Honpo',
  'Marza Animation Planet',
  'Khara',
  'Trigger',
  'yell',
  'KeyEast',
  'Dai-Ichi Douga',
  'Nihikime no Dozeu',
  'Vega Entertainment',
  '81 Produce',
  'Assez Finaud Fabric',
  'Gainax Kyoto',
  'Digital Network Animation',
  'Light Chaser Animation Studios',
  'Studio W.Baba',
  'Gear Studio',
  'Planet Nemo Animation',
  'Wonder Cat Animation',
  'Planet',
  'Office DCI',
  'Reiki Eyes Animation',
  'IMAGICA Lab.',
  'No Side',
  'Barnum Studio',
  'Panda Tower Studio',
  'Four Some',
  'Image House',
  'Studio Pivote',
  'Congrong Film',
  'Ruo Hong Culture',
  'Akatsuki',
  'Teatro Nishi Tokyo Studio',
  'MI',
  'Motion Magic',
  'Oh! Production',
  'Datama Film',
  'Haneda xR Studio',
  'Yuhodo',
  'Yonago Gainax',
  'PrimeTime',
  'Oddjob',
  'Sofix',
  'Studio 88',
  'studio ALBLE',
  'Creative House Pocket',
  'Qingxiang Culture',
  'Hayabusa Film',
  'Future Planet',
  'Radix',
  'VAP',
  'B.CMAY PICTURES',
  'Gunners',
  'Issen',
  'Arcturus',
  'SILVER LINK.',
  'Bandai Namco Filmworks',
  'A-1 Pictures',
  'MontBlanc Pictures',
  'Fukushima Gaina',
  'Gallop',
  'Twilight Town',
  'Cloud Art',
  'LB Commerce',
  'Chongzhuo Animation',
  'Hiro Media',
  'Tri-Slash',
  'Grouper Productions',
  'JM Animation',
  'Moss Design Unit',
  'Creatures Inc.',
  'Shenman Entertainment',
  'Benlai Pictures',
  'Tele-Cartoon Japan',
  'D & D Pictures',
  'Drive',
  'C2C',
  'Life Work',
  'Earth Design Works',
  'helo.inc',
  'Panmedia',
  'Spoon',
  'Studio Prokion',
  'Tsumupapa',
  'Tokyo Movie',
  'Picona',
  'Mook DLE',
  'Onionskin',
  'Itasca Studio',
  'Yinhe Changxing Culture',
  'Studio Coa',
  'Studio D-Volt',
  'Wawayu Animation',
  'soket',
  'Studio Korumi',
  'Hurray!',
  'Tokyo TV Douga',
  'Production I.G',
  'ORCEN',
  'Kinema Citrus',
  'Ijigen Tokyo',
  'MAPPA',
  'Horannabi',
  'Academy Productions',
  'Saber Project',
  'Jumonji',
  'Momoi Planning',
  'CHOCOLATE',
  'Eiken',
  'TrioPen Studio',
  'Neft Film',
  'CMAY Animation',
  'GoHands',
  'Guo Pengzi Studio',
  'BUG FILMS',
  'Sugata Creative & Design',
  'Toei Video',
  'Planet Cartoon',
  'MAT',
  'Sunwoo Entertainment',
  'KOO-KI',
  'HuaDream',
  'Odolttogi',
  'Doga Kobo',
  'Nakamura Production',
  'Plus Heads',
  'Team YokkyuFuman',
  'Artland',
  'TYO Animations',
  'Studio Rikka',
  'Rabbit Gate',
  'E&H Production',
  'Anime Beans',
  'Seven Arcs',
  'studio NAGURI',
  'Poly Animation',
  'Studio Polon',
  'Slow Studio',
  'Studio Himalaya',
  'Actas',
  'Imagestone Inc.',
  'Sankaku',
  'Nippon Animation',
  'Production D.M.H',
  'uzupiyo Animation & Digital Works',
  'Locus Corporation',
  'Maho Film',
  'R11R',
  'Sumomo Film',
  'Studio 9 Maiami',
  'Sunny Gapen',
  'Ten Tails Animation',
  'L²Studio',
  'Mushi Production',
  'Mimoid',
  'animate Film',
  'Studio Kelmadick',
  'Imagica',
  'AIC PLUS+',
  'Science SARU',
  'NHK Enterprises',
  'Telescreen',
  'Code',
  'Studio Palette',
  "STUDIO6'oN",
  'OutSide Directors Company',
  'Anime Antenna Iinkai',
  'Creators in Pack',
  'Studio Goindol',
  'Studio Kafka',
  'Scooter Films',
  'CCTV Animation',
  'Dynamic Planning',
  'Bellnox Films',
  'Husio Studio',
  'Bee Train',
  'W-Toon Studio',
  'Production Wave',
  'Goto Inc.',
  'GANSIS',
  'Studio Elle',
  'Cloud Culture',
  'PoRO',
  'CGCG Studio',
  'BYMENT',
  'Tonko House',
  'Studio Kikan',
  'HMCH',
  'ASTROBROS.',
  'Hotline',
  'Tsuchida Productions',
  '6pucks',
  'Seven Stone Entertainment',
  'Welz Animation Studios',
  'Foch Film',
  'Inugoya',
  'Youliao Studio',
  'Studio G7',
  'Ishimori Entertainment',
  'Circle Tribute',
  'Studio Ten Carat',
  'Alpha Animation',
  'Karaku',
  'iDRAGONS Creative Studio',
  'Studio Eight Color',
  'Manglobe',
  'Annapuru',
  'Studio N',
  'Kojiro Shishido Animation Works',
  'Studio Hibari',
  'Tatsunoko Production',
  'Shelty',
  'Dazzling Star',
  'Shadow Pond Studio',
  'Plum',
  'Shengguang Knight Culture',
  'Studio Junio',
  'Colored Pencil Animation Japan',
  'Platinum Vision',
  'Yudubai Animation',
  'Office TakeOut',
  'Image Studio 109',
  'Shengying Animation',
  'Anima&Co.',
  'NHK',
  'VROOOOM',
  'Arch',
  'Studio Soul',
  'Agent 21',
  'Gainax',
  'Avaco Creative Studios',
  'APPP',
  'Cloud Hearts',
  'Takun Manga Box',
  'Kantou Douga Kai',
  'AHA Entertainment',
  'Vasoon Animation',
  'Volca',
  'Sola Digital Arts',
  'A4A Inc.',
  'Blaze Studio',
  'Production GoodBook',
  'Taomee',
  'Studio Comet',
  'ROLL2',
  'SANZIGEN',
  'Escape Velocity Animation',
  'Circus Production',
  'Xing Xing Donghua',
  'Calf Studio',
  'Suna Kouhou',
  'Ultra Super Pictures',
  'Anime Tokyo',
  'Quebico',
  'MOJO Animation',
  'Anpro',
  'Drawing and Manual',
  'Paper Animation',
  'Windy Studio',
  'New Deer',
  'Studio B&M',
  'FIREBUG',
  'evg',
  'Makino Production',
  'Telecom Animation Film',
  'Amineworks',
  'STUDIOK110',
  'Heart & Soul Animation',
  'Studio HUIT',
  'Wang Film Productions',
  'Marone',
  'Creative Power Entertaining',
  'Studio OX',
  'Big Bang',
  'Asahi Production',
  'Studio Gadget',
  'Network Kouenji Studio',
  'Oriental Creative Color',
  'Geno Studio',
  'Ezόla',
  'MMDGP',
  'Daume',
  'C and R',
  'Passione',
  'LIDENFILMS Kyoto Studio',
  'Borutong',
  'Euluca Lab',
  'Alke',
  'Atti Production',
  'Kate Arrow',
  'Studio Kai',
  'Ocon Studio',
  'Grayscale Arts',
  'Hu Po Donghua',
  'XFLAG',
  'Shueisha',
  'studio hb',
  'Tengu Kobo',
  'Dancing CG Studio',
  'Shinjukuza',
  'Kaca Entertainment',
  'KIZAWA Studio',
  'Studio Ghibli',
  'Kassen',
  'Infinity Vision',
  'Tamura Shigeru Studio',
  'A-Real',
  'Kitty Film Mitaka Studio',
  'Heewon Entertainment',
  'Decovocal',
  '717 Animation Studio',
  'Indeprox',
  'CUCURI',
  'Particlefield',
  'Studio Button',
  'Hong Ying Animation',
  'Shaft',
  'Zero-G',
  'ORADA COMPANY',
  'Echoes',
  'Ai Si Animation Studio',
  'Qubic Pictures',
  'TEC',
  'Durufix',
  'Outline',
  'Kokusai Eigasha',
  'Coastline Animation Studio',
  'Nippon Columbia',
  'Oyster',
  'ONIRO',
  'Kitchen Ltd.',
  'Flying Ship Studio',
  'SynergySP',
  'monofilmo',
  'Mouse',
  'Studio Hakk',
  'CG Year',
  'Unend',
  'Bones',
  'Tsubo Production',
  'DMM.futureworks',
  'Magic Bus',
  'Tsuburaya Productions',
  'SEK Studios',
  'Spooky graphic',
  'Arms',
  'Brians Film',
  'Studio A-CAT',
  'Studio Add',
  'San-X',
  'CinePix',
  'Sovat Theater',
  'Youku',
  'Okuruto Noboru',
  'studio YOG',
  'Stingray',
  'Kaname Productions',
  'TANOsim',
  'Piko Studio',
  'Flavors Soft',
  'Blue Note',
  'Noovo',
  'Studio Lings',
  'Toyo Links Corporation',
  'Bridge',
  'Year Young Culture',
  'dwarf',
  'Ekura Animal',
  'Nagomi',
  'Animation 21',
  'Dynamo Pictures',
  'P core',
  'WonderLand',
  'Satelight',
  'Kuri Jikken Manga Koubou',
  'I & A',
  'Acca effe',
  'East Fish Studio',
  'Gyorai Eizo Inc.',
  'Frontier Works',
  'Kung Fu Frog Animation',
  'SIGNIF',
  'Aurum Production',
  'Studio Bogey',
  'Shikachan Studio',
  'CygamesPictures',
  'Otogi Production',
  'HAL Film Maker',
  'Super Brain',
  'Creators Dot Com',
  'Big Wing',
  'G&G Direction',
  'Miota',
  'HeART-BIT',
  'Gakken',
  'Potato House',
  'BUILD DREAM',
  'Studio Dadashow',
  'Garden Culture',
  'Flagship Line',
  'Shanghai Hippo Animation',
  'Kanaban Graphics',
  'BUDDHA INC.',
  'Yokohama Animation Laboratory',
  'Primastea',
  'David Production',
  'K-Factory',
  'Mili Pictures',
  'Nostalook',
  'Studio Blanc.',
  'AIC Frontier',
  'Craftar Studios',
  'Ekakiya',
  'Studio GOONEYS',
  'CLAP',
  'Studio Moe',
  'DR Movie',
  'Bones Film',
  'Animation Lab Japan',
  'C&S Production',
  'Minakata Laboratory',
  'Kami Kukan',
  'FOREST Hunting One',
  'Atelier Tuki',
  'Topcraft',
  'Enishiya',
  'Imagica Infos',
  'Ankama Animations',
  'DRAWIZ',
  'studio2 Animation Lab',
  'Artner',
  'Studio Moriken',
  'Gonzino',
  'Studio Kyuuma',
  'High Energy Studio',
  'Studio Cockpit',
  'Oxybot',
  'Big Pine Animation Studio',
  'Bee Media',
  'Qiyuan Yinghua',
  'Jinnan Studio',
  'Studio G-1Neo',
  'Bouncy',
  'Colored Pencil Animation',
  'Fengyun Animation',
  'Studio Boogie Nights',
  'Boyan Pictures',
  'Fuji TV',
  'Soigne',
  'AQUA ARIS',
  'Think Corporation',
  'XFLAG Pictures',
  'Shindeban Film',
  'Office Take Off',
  '924 Studio',
  'Aubec',
  'Kazami Gakuen Koushiki Douga-bu',
  'Flint Sugar',
  'Dimps',
  'Shion',
  'Teddy',
  'Studio Signpost',
  'Bakken Record',
  'I.Gzwei',
  "Steve N' Steven",
  'Gekkou',
  'Mainichi Eigasha',
  'M&M',
  'Sublimation',
  'Production HASU',
  'Qualia Animation',
  'Alpha Group',
  'Albacrow',
  "Ryuu M's",
  'Kent House',
  'ENGI',
  'Ashi Productions',
  'J.K.I',
  'CyberConnect2',
  'Studio Tumble',
  'Gosay Studio',
  '7doc',
  'Yamiken',
  'CANON RECORDINGS',
  'Automatic Flowers Studio',
  'Blade',
  'Whatever Co.',
  'Eallin',
  'Studio Wombat',
  'Studio Jin',
  'Atorie A.B.C.',
  'UchuPeople',
  'Le-joy Animation Studio',
  'Madhouse',
  'Pb Animation Co. Ltd.',
  'ILCASHIPS',
  'Kyushu Network Animation',
  'UWAN Pictures',
  'Rhythmos',
  'Meltdown',
  'Brio Animation',
  'MK Pictures',
  'Studio 4°C',
  'Steamworks',
  '5 Inc.',
  'Garyuu Studio',
  'TCJ',
  'Zero-G Room',
  'A-Line',
  'AIC',
  '10Gauge',
  'Pmats9 studio',
  'MMT Technology',
  'aNCHOR',
  'Transistor Studio',
  'Majin',
  'Rocen',
  'domerica',
  'KWANED',
  'TYMOTE',
  'Studio Kingyoiro',
  'Studio Ponoc',
  'Studio Outrigger',
  'Azeta Pictures',
  'Wei Chuang Jiang Xin',
  'I.Toon',
  'Sprite Animation Studios',
  'Gaina',
  'Tryforce',
  'Anon Pictures',
  'Yasuda Genshou Studio by Xenotoon',
  'Studio Ranmaru',
  'Tonari Animation',
  'CANOPUS',
  'Toei Animation',
  'Onion Studio',
  'Animaruya',
  'Kobito',
  'Wise Guy',
  'Team TillDawn',
  'CoMix Wave Films',
  'Pops Inc.',
  'Ginga Teikoku',
  'Asura Film',
  'miHoYoAnime',
  'AT-2',
  'Xebec',
  'ACiD FiLM',
  'Liberty Animation Studio',
  'CELAVIE',
  'Zelico Film',
  'Studio Artegg',
  'Alfred Imageworks',
  'Studio Jemi',
  'AIC Project',
  'EDP graphic works',
  'NANON CREATIVE',
  'Frontier One',
  'team Yamahitsuji',
  'Gathering',
  'ARCUS',
  'MASTER LIGHTS',
  'LICO',
  'Au Praxinoscope',
  'OLM',
  'Tomason',
  'Studio Take Off',
  'Soeishinsha',
  'Soft Garage',
  'Valkyria',
  'Keyring',
  'An DerCen',
  'StudioXD',
  'Nur',
  'HuaMei Animation',
  'Uguisu Kobo',
  '3D Co.',
  'TthunDer Animation',
  'Mirai Fusion',
  'Polygon Pictures',
  'Artmic',
  'Kaeruotoko Shokai',
  'Studio M2',
  'Studio Dolphin Night',
  'Peak Hunt',
  'teevee graphics',
  'Trash Studio',
  'Tokyo Media Connections',
  'Studio Colorido',
  'Grom',
  'MoMo Production',
  'Big Firebird Culture',
  'THINGS.',
  'Sega Interactive',
  'FAB',
  'Shuiniu Dongman',
  'DOGA Productions',
  'Shogakukan Music & Digital Entertainment',
  'Sugar Boy',
  'Trans Arts',
  'Japan Vistec',
  'Cutie Bee',
  'Nihon Ad Systems',
  'MooGoo',
  'Guton Animation Studio',
  'Mad Box',
  'Rikuentai',
  'Suzuki Mirano',
  'Pure Arts',
  'Fenz',
  'Pollyanna Graphics',
  'Ark',
  'Studio Z5',
  'Wolfsbane',
  'Mook Animation',
  'XEBEC M2',
  'Daewon Media',
  'Studio! Cucuri',
  'Sunny Side Up',
  'TOHO animation STUDIO',
  'LMD',
  'Studio Gale',
  'Imageworks Studio',
  'Digital Media Lab',
  'V-sign',
  'Darts',
  'Happy Elements',
  'Studio Ppuri',
  'Sharefun Studio',
  'Kamio Japan',
  'feel.',
  'ChuChu',
  'Hezmon Animation',
  'BloomZ',
  'Signal.MD',
  'Studio Ten',
  'JJJOY Animation Studios',
  'Ishibashi Planning',
  'Office Nobu',
  'RG Animation Studios',
  'GARDEN LODGE',
  'Lerche',
  'Qiying Animation',
  'Hutoon Animation',
  'Studio Gohan',
  'KSS',
  'SJYNEXCUS',
  'Jinnis Animation Studios',
  'WAO World',
  'Shura',
  'Comma Studio',
  'Twilight Studio',
  'Image Kei',
  'Sparky Animation',
  'Studio Animal',
  'Dream Entertainment',
  'Ginga Ya',
  'Studio Matrix',
  'New Generation',
  'Office AO',
  '100studio',
  'Flying Monkeys Production',
  'Composition Inc.',
  'Green Monster Team',
  'Trinet Entertainment',
  'Opera House',
  'Nomad',
  'Triple X',
  'Fever Creations',
  'Nut',
  'Buyuu',
  'Million Volt',
  'Quad',
  'ANYZAC',
  'Strawberry Meets Pictures',
  'Bibury Animation Studios',
  'Tomoyasu Murata Company',
  'Nexus',
  'Ascension',
  'Imagica Imageworks',
  'GRIZZLY',
  'N&G Production',
  'Blue Cat',
  'Quyue Technology',
  'Gakken Eigakyoku',
  'Xuni Ying Ye',
  'ABJ COMPANY',
  'd00r works',
  'Saigo no Shudan',
  'Nippon TV Douga',
  'PP Project',
  'Studio Fusion',
  'Project Team Sarah',
  'IKK Room',
  'STUDIO 8 DOGS',
  'Studio Fantasia',
  'Connect',
  'HoriPro',
  'FILMONY',
  'J.C.Staff',
  'Beat Frog',
  'Kachidoki Studio',
  'TypeZero',
  'Central Animation Studio',
  'Studio Sota',
  'Khaki',
  'Beijing Huihuang Animation Company',
  'Karasfilms',
  'Studio Barcelona',
  'Starry Cube',
  'Buemon',
  'Cafe de Jeilhouse',
  'Movic',
  'Giga Production',
  'EOEO System',
  'Rabbit Machine',
  'J.C.F.',
  'Studio DURIAN',
  'Production +h.',
  'BreakBottle',
  '1IN',
  'Aiti St.',
  'ufotable',
  'AMGA',
  'Idea Factory',
  'Speed Inc.',
  'G&G Entertainment',
  'Delpic',
  'Melissa',
  'Tezuka Productions',
  'TMS Entertainment',
  'Pierrot',
  'Studio Bingo',
  'Caviar',
  'Bandai Namco Pictures',
  'Beijing Enlight Pictures',
  'Arcs Create',
  'Bibury Animation CG',
  'lxtl',
  'JCF',
  'Painted Blade Studio',
  'Imagin',
  'Seven Arcs Pictures',
  'Concept Films',
  'Ice Butter',
  'Studio 1st',
  'KKC Animation Production',
  'Keica',
  'Lyrics',
  'Phoenix Entertainment',
  'Studio KeepFire',
  'Paper Plane Animation Studio',
  'Knack Productions',
  'Mippei Eigeki Kiryuukan',
  'Kamikaze Douga',
  'Ether Kitten',
  'Studio BAZOOKA',
  'Sanrio',
  'Axis',
  'HIDEHOMARE',
  'Poncotan',
  'AION Studio',
  'Kenji Studio',
  'Dangun Pictures',
  'LIDENFILMS Osaka Studio',
  'Panda Factory',
  'Bigcat Studio',
  'Diomedéa',
  'Gonzo',
  "D'ART Shtajio",
  'Nippon Ramayana Film Co.',
  'Point Pictures',
  'Sanctuary',
  'CMC Media',
  'Studio Live',
  'Typhoon Graphics',
  'Makaria',
  'Staple Entertainment',
  'LIGHTAIR Inc.',
  'Studio Deen',
  'Visual Flight',
  'ORENDA',
  'ACC Production',
  'YURUPPE Inc.',
  'Shuka',
  'Hero',
  'The Village of Marchen',
  'DLE',
  'Studio UGOKI',
  'Silver',
  'Studio Matomo',
  'SBS TV Production',
  'Tang Kirin Culture',
  'DAX Production',
  'Romanov Films',
  'Tecarat',
  'G.P Entertainment',
  'Tomovies',
  'Studio Mir',
  'Enjin Productions',
  'Sunflowers',
  'EOTA',
  'Picture Magic',
  'Puzzle Animation Studio Limited',
  'Magia Doraglier',
  'Sotsu',
  'Purple Cow Studio Japan',
  'Animation Do',
  'Saetta',
  'Maxilla',
  'Laftel',
  'G-Lam',
  'StoryRiders Co. Ltd.',
  'cogitoworks',
  'JOF',
  'Ai Yume Mai',
  'RAMS',
  'Jumondo',
  'Dongwoo A&E',
  'Manaa Animation',
  'Venet',
  'GAV Video',
  'HS Pictures Studio',
  'Zexcs',
  'Adonero',
  'Office No. 8',
  'Studio Pastoral',
  'AIC Takarazuka',
  'Lesprit',
  'Enzo Animation',
  'Spell Bound',
  'Digital Frontier',
  'TROYCA',
  'Team OneOne',
  'Transcendence Picture',
  'Studio Gram',
  'Aiko',
  'Nihon Hoso Eigasha',
  'Cyclone Graphics',
  'AXsiZ',
  'Ripromo',
  'Public Enemies',
  'Pink Cat',
  'Tear Studio',
  'Next Media Animation',
  'Sunrise Beyond',
  'Voil',
  'Studio Clutch',
  'Ajia-do',
  'Egg Firm',
  'MB planning',
  'Suoyi Technology',
  'Anime R',
  'Himajin Planning',
  'Piso Studio',
  'ANIDO FILM',
  'Blue bread',
  'Square Enix Visual Works',
  'flag Co.',
  "Brain's Base",
  'Emon',
  'Orange',
  'TNK',
  'Indivision',
  'Pierrot Plus',
  'Magma Studio',
  'Pie in the sky',
  'Production Reed',
  'Takara Tomy A.R.T.S',
  'Asmik Ace',
  'W+K Tokyo',
  'Brick Studio',
  'Studio Gokumi',
  'Tsumugi Akita Animation Lab',
  'Triangle Staff',
  'Hananona Studio',
  'Group Creato',
  'Imagineer',
  'Usagi Ou',
  'Gravity Well',
  'Directions',
  'Original Force',
  'Chosen',
  'Oz Inc.',
  'Atelier Pontdarc',
  'EMT Squared',
  'Studio Chizu',
  'LIDENFILMS',
  'Robot Communications',
  'Animation Planet',
  'Studio Guts',
  'Wong Ping Animation Lab',
  'Geek Toys',
  'Nekonigashi Inc.',
  'Fugaku',
  'AIC ASTA',
  'FUNNY MOVIE',
  'Kyotoma',
  'Hololive Production',
  'I-move',
  'Studio World',
  'Suspenders',
  'SELFISH',
  'Visual 80',
  'Wit Studio',
  'Contrail',
  'DandeLion Animation Studio',
  'Liyu Culture',
  'Andraft',
  'PERIMETRON',
  'Filmlink International',
  'happyproject',
  'Shin-Ei Animation',
  'Sanrio Digital',
  'Studio Lemon',
  'Animation Staff Room',
  'Sakura Create',
  'Kuai Ying Hu Yu',
]
